--저장
--3
SELECT * FROM TB_BOOK;
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

--4
SELECT * FROM TB_WRITER;

SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM(SELECT *
FROM TB_WRITER
WHERE SUBSTR(MOBILE_NO,1,3) = '019'
AND SUBSTR(WRITER_NM,1,1) = '김'
ORDER BY WRITER_NM)
WHERE ROWNUM = 1;

--5
SELECT * FROM TB_BOOK_AUTHOR;
SELECT * FROM TB_WRITER;

SELECT COUNT(DISTINCT WRITER_NO) AS "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김'
GROUP BY COMPOSE_TYPE;

--6
SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK_AUTHOR;

SELECT COMPOSE_TYPE, COUNT(*)
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
WHERE COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING COUNT(*) >= 300;

--7
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM (SELECT *
        FROM TB_BOOK
        ORDER BY ISSUE_DATE DESC)
WHERE ROWNUM = 1;

--8
SELECT * FROM TB_WRITER;
SELECT * FROM TB_BOOK_AUTHOR;
SELECT * FROM TB_BOOK;

SELECT * 
FROM (SELECT WRITER_NM AS "작가", COUNT(*) AS "권 수"
    FROM TB_BOOK
    JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
    JOIN TB_WRITER USING(WRITER_NO)
    GROUP BY WRITER_NM
    ORDER BY COUNT(*) DESC)
WHERE ROWNUM<=3;


--9
-- 책발행일 묶어서 작가넘버로 그룹 하고 거기에서 최소값찾ㅈ기
SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK_AUTHOR;
SELECT * FROM TB_WRITER;

UPDATE TB_WRITER W
SET REGIST_DATE = (SELECT MIN(ISSUE_DATE)
                    FROM TB_BOOK_AUTHOR
                    JOIN TB_BOOK USING(BOOK_NO)
                    WHERE W.WRITER_NO = WRITER_NO);
                       
SELECT * FROM TB_WRITER;                       
COMMIT;   

--10
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10) NOT NULL CONSTRAINT FK_BOOK_TRANSLATOR_01 REFERENCES TB_BOOK,
    WRITER_NO VARCHAR2(10) NOT NULL CONSTRAINT FK_BOOK_TRANSLATOR_02 REFERENCES TB_WRITER,
    TRANS_LANG VARCHAR2(60),
    CONSTRAINT PK_BOOK_TRANSLAROT PRIMARY KEY(BOOK_NO, WRITER_NO)
);

--11
SELECT * FROM TB_BOOK_AUTHOR;

SELECT * FROM TB_BOOK_TRANSLATOR;

INSERT ALL
INTO TB_BOOK_TRANSLATOR(BOOK_NO, WRITER_NO)
SELECT BOOK_NO, WRITER_NO
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN('옮김','역주','편역','공역');

DELETE FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN('옮김','역주','편역','공역');

--12
SELECT * FROM TB_BOOK_TRANSLATOR;

SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK_TRANSLATOR;
SELECT * FROM TB_WRITER;

SELECT BOOK_NM,WRITER_NM, ISSUE_DATE
FROM TB_BOOK_TRANSLATOR
JOIN TB_BOOK USING(BOOK_NO)
WHERE EXTRACT(YEAR FROM ISSUE_DATE) = '2007';

--13
--뷰를 생성해야됨.
SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK_TRANSLATOR;
SELECT * FROM TB_WRITER;

GRANT CREATE VIEW TO FINAL;

CREATE OR REPLACE VIEW VW_BOOK_TRANSLATOR
AS SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
    FROM TB_BOOK
    JOIN TB_BOOK_TRANSLATOR USING(BOOK_NO)
    JOIN TB_WRITER USING(WRITER_NO)
    WHERE EXTRACT(YEAR FROM ISSUE_DATE) = '2007'
    WITH READ ONLY;
SELECT * FROM VW_BOOK_TRANSLATOR;

--14
SELECT * FROM TB_PUBLISHER;
INSERT INTO TB_PUBLISHER VALUES('춘 출판사','02-6710-3737',DEFAULT);
COMMIT;

--15
SELECT * FROM TB_WRITER;
--동명이인 
SELECT WRITER_NM, COUNT(*)
FROM TB_WRITER
GROUP BY WRITER_NM
HAVING COUNT(*)>1;

--16
UPDATE TB_BOOK_AUTHOR
SET COMPOSE_TYPE = '지음'
WHERE COMPOSE_TYPE IS NULL;
SELECT * FROM TB_BOOK_AUTHOR;
COMMIT;

--17
SELECT * FROM TB_WRITER;
SELECT WRITER_NM, OFFICE_TELNO
FROM TB_WRITER
WHERE OFFICE_TELNO LIKE '02%'
AND OFFICE_TELNO LIKE '%-___-%';

--18
SELECT * FROM TB_WRITER;
SELECT WRITER_NM
FROM TB_WRITER
WHERE FLOOR(MONTHS_BETWEEN( TO_DATE(20060101),REGIST_DATE)/12)>=31
ORDER BY 1;

--19
SELECT* FROM TB_PUBLISHER;
SELECT * FROM TB_BOOK;
SELECT BOOK_NM, PRICE AS 가격,CASE WHEN STOCK_QTY<5 THEN '추가주문필요'
                    ELSE '소량보유'
                    END AS 재고상태
FROM TB_BOOK
WHERE PUBLISHER_NM = '황금가지'
AND STOCK_QTY <10;

--20
SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK_AUTHOR;
SELECT * FROM TB_WRITER;
SELECT * FROM TB_BOOK_TRANSLATOR;

SELECT BOOK_NM, W.WRITER_NM, W1.WRITER_NM
FROM TB_BOOK B
JOIN TB_BOOK_AUTHOR A ON(B.BOOK_NO = A.BOOK_NO)
JOIN TB_WRITER W USING(WRITER_NO)
JOIN TB_BOOK_TRANSLATOR T ON(B.BOOK_NO = T.BOOK_NO)
JOIN TB_WRITER W1 ON(W1.WRITER_NO = T.WRITER_NO)
WHERE BOOK_NM = '아타트롤';

--21
SELECT * FROM TB_BOOK;
SELECT * FROM TB_BOOK;


SELECT BOOK_NM 도서명, STOCK_QTY 재고, PRICE AS "ORG", CASE WHEN STOCK_QTY>=90 THEN PRICE*0.8 ELSE PRICE END AS "NEW"
FROM TB_BOOK
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM ISSUE_DATE) >=30
AND STOCK_QTY >=90
ORDER BY 2 DESC,4 DESC ,1 ;
