SELECT SYSDATE
FROM DUAL;

SELECT LENGTH('오라클'), LENGTHB('오라클')
FROM DUAL;

SELECT LENGTH('ORACLE'), LENGTHB('ORACLE') FROM DUAL;

SELECT EMP_NAME, LENGTH(EMP_NAME) 
FROM EMPLOYEE;

-- INSTAR(컬럼|'리터럴', '찾고자하는 문자', 시작 지점, 몇번째 문자?)

SELECT INSTR('AAAADDDDDCCCCB', 'B') FROM DUAL; 

SELECT INSTR('AAAABDDDDCCBDDB', 'B',1)
FROM DUAL;

SELECT INSTR('AAAABDDDDCCBDDB', 'B',-1)
FROM DUAL;

SELECT INSTR('AAAABDDDDCCBDDB', 'B',1,2)
FROM DUAL;

SELECT INSTR(EMAIL,'@') || '번째' AS "@위치"
FROM EMPLOYEE;

SELECT SUBSTR('SHOWMETHEMONEY',1,4) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',5,2) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',1,6) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',-8,3) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',1,-4) FROM DUAL; -- 길이는 양수만 됨.

SELECT *
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,8,1) = '2';

SELECT *
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,8,1) = '1';

SELECT EMP_NAME, EMAIL, SUBSTR(EMAIL,1, INSTR(EMAIL,'@')-1)
FROM EMPLOYEE;

SELECT EMP_NAME, LPAD(EMAIL,20)
FROM EMPLOYEE;

SELECT EMP_NAME, LPAD(EMAIL,20,'#')
FROM EMPLOYEE;

SELECT EMP_NAME, RPAD(EMAIL, 20)
FROM EMPLOYEE;

--850101-2******나오게 조회 => 총 14글자.

SELECT *
FROM EMPLOYEE;

SELECT RPAD(SUBSTR(EMP_NO,1,INSTR(EMP_NO,'-')+1),14,'*') AS "주민번호"
FROM EMPLOYEE;